# Generated by Django 4.2 on 2024-05-29 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storylike',
            name='story',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='story_likes', to='stories.story'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='story',
            name='points',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
