# Generated by Django 4.2 on 2024-05-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article_comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
