# Generated by Django 4.2 on 2024-05-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('articles', '0001_initial'),
        ('stories', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmark_article',
            field=models.ManyToManyField(related_name='bookmarked', to='articles.article'),
        ),
        migrations.AddField(
            model_name='user',
            name='bookmark_story',
            field=models.ManyToManyField(related_name='bookmarked', to='stories.story'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_article',
            field=models.ManyToManyField(related_name='liked', to='articles.article'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_story',
            field=models.ManyToManyField(related_name='liked', to='stories.story'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
