# Generated by Django 4.2 on 2024-05-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('stories', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bookmark_article',
            field=models.ManyToManyField(blank=True, related_name='bookmarked', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bookmark_story',
            field=models.ManyToManyField(blank=True, related_name='bookmarked', to='stories.story'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_article',
            field=models.ManyToManyField(blank=True, related_name='liked', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_story',
            field=models.ManyToManyField(blank=True, related_name='liked', to='stories.story'),
        ),
    ]
