nations = [
    ("Argentina", "Argentina"),
    ("Australia", "Australia"),
    ("Austria", "Austria"),
    ("Bangladesh", "Bangladesh"),
    ("Belarus", "Belarus"),
    ("Belgium", "Belgium"),
    ("Bolivia", "Bolivia"),
    ("Brazil", "Brazil"),
    ("Cambodia", "Cambodia"),
    ("Canada", "Canada"),
    ("Chile", "Chile"),
    ("China", "China"),
    ("Colombia", "Colombia"),
    ("Croatia", "Croatia"),
    ("Egypt", "Egypt"),
    ("France", "France"),
    ("Germany", "Germany"),
    ("Greece", "Greece"),
    ("Hungary", "Hungary"),
    ("Iceland", "Iceland"),
    ("India", "India"),
    ("Indonesia", "Indonesia"),
    ("Israel", "Israel"),
    ("Italy", "Italy"),
    ("Japan", "Japan"),
    ("Jordan", "Jordan"),
    ("Kazakhstan", "Kazakhstan"),
    ("Kuwait", "Kuwait"),
    ("Malaysia", "Malaysia"),
    ("Mexico", "Mexico"),
    ("Mongolia", "Mongolia"),
    ("Morocco", "Morocco"),
    ("Myanmar", "Myanmar"),
    ("Netherlands", "Netherlands"),
    ("New Zealand", "New Zealand"),
    ("Pakistan", "Pakistan"),
    ("Papua New Guinea", "Papua New Guinea"),
    ("Philippines", "Philippines"),
    ("Poland", "Poland"),
    ("Qatar", "Qatar"),
    ("Russia", "Russia"),
    ("Saudi Arabia", "Saudi Arabia"),
    ("Singapore", "Singapore"),
    ("South Africa", "South Africa"),
    ("Spain", "Spain"),
    ("Sri Lanka", "Sri Lanka"),
    ("Sweden", "Sweden"),
    ("Switzerland", "Switzerland"),
    ("Taiwan", "Taiwan"),
    ("Thailand", "Thailand"),
    ("Turkey", "Turkey"),
    ("United Arab Emirates", "United Arab Emirates"),
    ("United Kingdom", "United Kingdom"),
    ("USA", "USA"),
    ("Uzbekistan", "Uzbekistan"),
    ("Vietnam", "Vietnam"),
]
